### ISSUE TITLE
what is INIT_OFFSET ? 

### ISSUE THREAD

**Issue by erfanoabdi** [freddierice/trident#2]
Hi freddierice, thanks for this amazing tool but i want to modify it to make it work with other phones 
where i can get the init offset of my device ?
should i disassemble my init binary at ramdisk files? 

and one more question 
can we load modified sepolicy with this tool https://forum.xda-developers.com/android/software/setools-android-sepolicy-inject-t2977563   ?

thanks alot

**Comment by freddierice** [comment]
> Hi freddierice, thanks for this amazing tool but i want to modify it to make it work with other phones
where i can get the init offset of my device ?
should i disassemble my init binary at ramdisk files?

Yes.

> and one more question
can we load modified sepolicy with this tool https://forum.xda-developers.com/android/software/setools-android-sepolicy-inject-t2977563 ?

I created my modified sepolicy file with that tool (as referenced in the readme)

**Comment by erfanoabdi** [comment]
thanks for reply 
i found your blog https://www.redtile.io/security/galaxy/
it has very good informations  
adding that url in README would be nice because first time i found this repo then after too many searching i found out init_offset belongs to bootchart_sample in your blog

thanks again
